#Configuration.
[mqtt]
server="tcp://localhost:1883"
user="your-user"
password="your-password"

[gateway]
mac="your-gw-mac"

[band]
name="US_902_928"

[device]
eui="0000000000000001"
address="00815bd9"
network_session_encription_key="aee1da4b88979ae4f75475ff0db51c04"
serving_network_session_integrity_key="e0422b2a0307f24b2986e5b24ca8d3d9"
forwarding_network_session_integrity_key="bc97ea1ff62e7a3490135d989aae6bca"
application_session_key="037882c03dd6b20724b44d623abb4f95"
marshaler="json"
nwk_key="00000000000000010000000000000001"
app_key="00000000000000010000000000000001"
major=0
mac_version=1

[data_rate]
bandwith=125
spread_factor=10
bit_rate=0

[rx_info]
channel=0
code_rate="4/5"
crc_status=1
frequency=902300000
lora_snr=7.0
rf_chain=1
rssi=-57

[raw_payload]
payload="ff00"
use_payload=true